### PR TITLE
Add Hilt as a child of the Dependency Injection category

### PR DESCRIPTION
**Pull request by NitramTasu**
## Description
Add Hilt as a dependency injection library and child of Dagger, because it is recommended to start with Dagger, which is used longer than Hilt. After learning Dagger it will be easier to learn Hilt as it is built on it.

[Hilt Documentation](https://developer.android.com/training/dependency-injection/hilt-android)

## Image
image

### CODE REVIEW

**Comment by TWiStErRob** [comment]
It should be next to Dagger, as it is built on it. And you need to understand half of Dagger to use at the minimum, isn't it?

**Comment by NitramTasu** [comment]
> It should be next to Dagger, as it is built on it. And you need to understand half of Dagger to use at the minimum, isn't it?

I agree. Are you thinking like below or Hilt be a child of Dagger?
image

**Comment by TWiStErRob** [comment]
I was thinking below, but now that mention child makes more sense.

**Comment by NitramTasu** [comment]
Yep! I made the change.

**Comment by drcabral** [comment]
Hi everyone, thanks for the contributing and for the discuss!

**Review by drcabral — APPROVED** [review]

**Pull request merged**
